### ISSUE TITLE
Help Need

### ISSUE THREAD

**Issue by wifirevaithi** [fiso/smooth-bankid#4]
Hi,

  Can you help me to implement bankid login with flutter and i've some doubts with testbankid integration

**Comment by fiso** [comment]
I'd be happy to help out. What is the problem you're having?

**Comment by wifirevaithi** [comment]
i need to implement bankid login with flutter what i need to do can you give a step by step guide?

**Comment by wifirevaithi** [comment]
> I'd be happy to help out. What is the problem you're having?

please help me i can't get any way

**Comment by fiso** [comment]
@wifirevaithi What problems are you having exactly? What does your code look like? How are you making http requests?
